name: leechineo_panel
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^6.3.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.0
  flutter_svg: ^2.0.7
  uuid: ^3.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  path: ^1.8.3
  file_picker: ^5.3.3
  mime: ^1.0.4
  http_parser: ^4.0.2
  loading_indicator: ^3.1.1
  data_table_2: ^2.5.6
  # window_manager: ^0.3.5
  mask_text_input_formatter: ^2.5.0
  flutter_colorpicker: ^1.0.3
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  process_run: ^0.14.2
  socket_io_client: ^2.0.3+1
  flutter_localizations:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/Ilustrations/undraw/
    - assets/Ilustrations/app/
    - assets/bin/linux/
    - assets/bin/windows/
